### ISSUE TITLE
Apple II Schematic error

### ISSUE THREAD

**Issue by reifsnyderb** [baldengineer/bit-preserve#125]
On the Apple II Schematic, IO_STB off of F3 (74LS138), should be marked as follows:

IO Strobe - goes to all Peripheral Connectors (slots)
Goes low when accessing address range C800-CFFF

**Comment by baldengineer** [comment]
FYI, It looks like the original submitter for the Apple II and II+ schematic either re-used the design or heavily based on the II+ on the II. 

I didn't realize that when I looked closer at the II+. So, I have put significant work into repairing that schematic. My plan was to "back-port" that one to the II design later.

We'll take feedback on either! But if you are doing a deep dive review, the II+ might be a better choice since it's a bit more active and has already had a number of corrections.

**Comment by baldengineer** [comment]
For the most part, the only significant difference between the II and II+
(in terms of hardware) is the ROM. There were other minor changes, but the
vast majority of the chips are the same.

**Comment by baldengineer** [comment]
Addressed in 2e13763 for the II+ schematic. The II schematic will get "fixed" when in a future effort.
